### ISSUE TITLE
Alpha release todo

### ISSUE THREAD

**Issue by Giuliopime** [Giuliopime/ZenBreak#1]
**Common**
- [ ] App info section
**Desktop common**
- [ ] Popup UI
- [ ] Start at login
- [ ] Detect idling
**Linux**  
- [ ] Needs testing
**Windows**  
- [ ] Test
**MacOS**
- [ ] Native UI
- [ ] Open above fullscreen windows
**Android**
- [ ] Schedule with Work Manager / Foreground services
- [ ] Add notification panel shortcut
- [ ] Make widget?
**iOS**
- [ ] Schedule with background tasks
- [ ] Shortcut?
- [ ] SwiftUI instead of Compose?
